// src/components/canvas/components/CheckboxGroupComponent.vue
<template>
  <div :style="wrapperStyle">
    <label
      v-for="(option, idx) in options"
      :key="idx"
      class="checkbox-item"
      :class="{ interactive: isPreview }"
    >
      <input
        type="checkbox"
        :value="option"
        :checked="isPreview ? localValues.includes(option) : defaultValues.includes(option)"
        :disabled="!isPreview"
        @change="toggleOption(option)"
      />
      <span :style="labelStyle">{{ option }}</span>
    </label>
  </div>
</template>

<script setup lang="ts">
import { computed, inject, ref } from 'vue'
import type { ComponentData } from '@/types'

const props = defineProps<{ component: ComponentData }>()

const isPreview = inject('isPreview', false)

const options = computed(
  () => (props.component.props.options as string[] | undefined) ?? [],
)

const defaultValues = computed(
  () => (props.component.props.defaultValues as string[] | undefined) ?? [],
)

const localValues = ref<string[]>([...defaultValues.value])

function toggleOption(option: string) {
  const idx = localValues.value.indexOf(option)
  if (idx === -1) localValues.value.push(option)
  else localValues.value.splice(idx, 1)
}

const wrapperStyle = computed(() => ({
  width: '100%',
  height: '100%',
  boxSizing: 'border-box' as const,
  display: 'flex',
  flexDirection: 'column' as const,
  justifyContent: 'center',
  gap: '8px',
  padding: '8px 12px',
  backgroundColor: props.component.style.backgroundColor ?? '',
}))

const labelStyle = computed(() => ({
  fontSize: props.component.style.fontSize ? `${props.component.style.fontSize}px` : '14px',
  color: props.component.style.color ?? '#333333',
}))
</script>

<style scoped>
.checkbox-item {
  display: flex;
  align-items: center;
  gap: 6px;
  cursor: default;
  user-select: none;
}

.checkbox-item.interactive {
  cursor: pointer;
}

.checkbox-item input[type='checkbox'] {
  cursor: default;
  flex-shrink: 0;
}

.checkbox-item.interactive input[type='checkbox'] {
  cursor: pointer;
}
</style>

// src/components/canvas/components/CheckboxGroupComponent.tsx
import { useState, useMemo, useCallback } from 'react'
import type { ComponentData } from '@/types'
import { useIsPreview } from '@/context/PreviewContext'

export default function CheckboxGroupComponent({ component }: { component: ComponentData }) {
  const isPreview = useIsPreview()
  const options = (component.props.options as string[]) ?? []
  const defaultValues = (component.props.defaultValues as string[]) ?? []
  const [localValues, setLocalValues] = useState<string[]>([...defaultValues])

  const toggleOption = useCallback((option: string) => {
    setLocalValues((prev) =>
      prev.includes(option) ? prev.filter((v) => v !== option) : [...prev, option],
    )
  }, [])

  const wrapperStyle = useMemo<React.CSSProperties>(
    () => ({
      width: '100%',
      height: '100%',
      boxSizing: 'border-box',
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      gap: 8,
      padding: '8px 12px',
      backgroundColor: component.style.backgroundColor ?? '',
    }),
    [component.style.backgroundColor],
  )

  const labelStyle = useMemo<React.CSSProperties>(
    () => ({
      fontSize: component.style.fontSize ? `${component.style.fontSize}px` : '14px',
      color: component.style.color ?? '#333',
    }),
    [component.style.fontSize, component.style.color],
  )

  return (
    <div style={wrapperStyle}>
      {options.map((option, idx) => (
        <label
          key={idx}
          style={{
            display: 'flex',
            alignItems: 'center',
            gap: 6,
            cursor: isPreview ? 'pointer' : 'default',
            userSelect: 'none',
          }}
        >
          <input
            type="checkbox"
            value={option}
            checked={isPreview ? localValues.includes(option) : defaultValues.includes(option)}
            disabled={!isPreview}
            onChange={() => toggleOption(option)}
          />
          <span style={labelStyle}>{option}</span>
        </label>
      ))}
    </div>
  )
}
