// src/components/canvas/components/RadioGroupComponent.tsx
import { useState, useMemo } from 'react'
import type { ComponentData } from '@/types'
import { useIsPreview } from '@/context/PreviewContext'

export default function RadioGroupComponent({ component }: { component: ComponentData }) {
  const isPreview = useIsPreview()
  const options = (component.props.options as string[]) ?? []
  const defaultValue = (component.props.defaultValue as string) ?? ''
  const [localValue, setLocalValue] = useState(defaultValue)

  const wrapperStyle = useMemo<React.CSSProperties>(
    () => ({
      width: '100%',
      height: '100%',
      boxSizing: 'border-box',
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      gap: 8,
      padding: '8px 12px',
      backgroundColor: component.style.backgroundColor ?? '',
    }),
    [component.style.backgroundColor],
  )

  const labelStyle = useMemo<React.CSSProperties>(
    () => ({
      fontSize: component.style.fontSize ? `${component.style.fontSize}px` : '14px',
      color: component.style.color ?? '#333',
    }),
    [component.style.fontSize, component.style.color],
  )

  return (
    <div style={wrapperStyle}>
      {options.map((option, idx) => (
        <label
          key={idx}
          style={{
            display: 'flex',
            alignItems: 'center',
            gap: 6,
            cursor: isPreview ? 'pointer' : 'default',
            userSelect: 'none',
          }}
        >
          <input
            type="radio"
            name={`radio-${component.id}`}
            value={option}
            checked={option === (isPreview ? localValue : defaultValue)}
            disabled={!isPreview}
            onChange={() => setLocalValue(option)}
          />
          <span style={labelStyle}>{option}</span>
        </label>
      ))}
    </div>
  )
}

// src/components/canvas/components/RadioGroupComponent.vue
<template>
  <div :style="wrapperStyle">
    <label
      v-for="(option, idx) in options"
      :key="idx"
      class="radio-item"
      :class="{ interactive: isPreview }"
    >
      <input
        type="radio"
        :name="`radio-${component.id}`"
        :value="option"
        :checked="option === (isPreview ? localValue : defaultValue)"
        :disabled="!isPreview"
        @change="localValue = option"
      />
      <span :style="labelStyle">{{ option }}</span>
    </label>
  </div>
</template>

<script setup lang="ts">
import { computed, inject, ref } from 'vue'
import type { ComponentData } from '@/types'

const props = defineProps<{ component: ComponentData }>()

const isPreview = inject('isPreview', false)

const options = computed(() => (props.component.props.options as string[] | undefined) ?? [])

const defaultValue = computed(
  () => (props.component.props.defaultValue as string | undefined) ?? '',
)

const localValue = ref(defaultValue.value)

const wrapperStyle = computed(() => ({
  width: '100%',
  height: '100%',
  boxSizing: 'border-box' as const,
  display: 'flex',
  flexDirection: 'column' as const,
  justifyContent: 'center',
  gap: '8px',
  padding: '8px 12px',
  backgroundColor: props.component.style.backgroundColor ?? '',
}))

const labelStyle = computed(() => ({
  fontSize: props.component.style.fontSize ? `${props.component.style.fontSize}px` : '14px',
  color: props.component.style.color ?? '#333333',
}))
</script>

<style scoped>
.radio-item {
  display: flex;
  align-items: center;
  gap: 6px;
  cursor: default;
  user-select: none;
}

.radio-item.interactive {
  cursor: pointer;
}

.radio-item input[type='radio'] {
  cursor: default;
  flex-shrink: 0;
}

.radio-item.interactive input[type='radio'] {
  cursor: pointer;
}
</style>
