// src/components/canvas/components/TextareaComponent.tsx
import { useState, useMemo, useEffect } from 'react'
import type { ComponentData } from '@/types'
import { useComponentStyle } from '@/hooks/useComponentStyle'
import { useIsPreview } from '@/context/PreviewContext'
import { useEditorStore } from '@/stores/editorStore'

export default function TextareaComponent({ component }: { component: ComponentData }) {
  const baseStyle = useComponentStyle(component.style)
  const isPreview = useIsPreview()
  const validationErrors = useEditorStore((s) => s.validationErrors)
  const setPreviewValue = useEditorStore((s) => s.setPreviewValue)
  const [localValue, setLocalValue] = useState('')
  const errorMessage = validationErrors[component.id] ?? ''

  useEffect(() => {
    if (isPreview) setPreviewValue(component.id, localValue)
  }, [localValue])

  const style = useMemo<React.CSSProperties>(
    () => ({
      ...baseStyle,
      color: component.style.color ?? '#333',
      backgroundColor: component.style.backgroundColor ?? '#fff',
      border: '1px solid #dcdfe6',
      borderRadius: component.style.borderRadius ? `${component.style.borderRadius}px` : '4px',
      padding: '8px 12px',
      resize: 'none',
      outline: 'none',
      fontFamily: 'inherit',
    }),
    [baseStyle, component.style],
  )

  return (
    <div style={{ position: 'relative', width: '100%', height: '100%' }}>
      <textarea
        placeholder={(component.props.placeholder as string) ?? '\u8bf7\u8f93\u5165\u5185\u5bb9'}
        rows={(component.props.rows as number) ?? 4}
        maxLength={(component.props.maxlength as number) || undefined}
        readOnly={!isPreview}
        style={style}
        onChange={(e) => {
          if (isPreview) setLocalValue(e.target.value)
        }}
      />
      {errorMessage && (
        <span
          style={{
            position: 'absolute',
            top: '100%',
            left: 0,
            fontSize: 11,
            color: '#f56c6c',
            marginTop: 2,
          }}
        >
          {errorMessage}
        </span>
      )}
    </div>
  )
}

// src/components/canvas/components/TextareaComponent.vue
<template>
  <div class="textarea-wrapper">
    <textarea
      class="textarea-component"
      :placeholder="(component.props.placeholder as string) ?? '请输入内容'"
      :rows="(component.props.rows as number) ?? 4"
      :maxlength="(component.props.maxlength as number) || undefined"
      :readonly="!isPreview"
      :style="textareaStyle"
      @input="handleInput"
    />
    <span v-if="errorMessage" class="validation-error">{{ errorMessage }}</span>
  </div>
</template>

<script setup lang="ts">
import { computed, inject, ref, watch } from 'vue'
import type { Ref } from 'vue'
import type { ComponentData } from '@/types'
import { useComponentStyle } from './composables/useComponentStyle'
import { useEditorStore } from '@/stores/editor'

const props = defineProps<{ component: ComponentData }>()

const isPreview = inject<Ref<boolean>>('isPreview', ref(false))
const editorStore = useEditorStore()
const localValue = ref('')

const { baseStyle } = useComponentStyle(props.component.style)

const textareaStyle = computed(() => ({
  ...baseStyle.value,
  color: props.component.style.color ?? '#333333',
  backgroundColor: props.component.style.backgroundColor ?? '#ffffff',
  border: '1px solid #dcdfe6',
  borderRadius: props.component.style.borderRadius
    ? `${props.component.style.borderRadius}px`
    : '4px',
  padding: '8px 12px',
  resize: 'none' as const,
}))

const errorMessage = computed(() => editorStore.validationErrors[props.component.id] ?? '')

const handleInput = (e: Event) => {
  if (!isPreview.value) return
  localValue.value = (e.target as HTMLTextAreaElement).value
}

watch(localValue, (val) => {
  if (isPreview.value) editorStore.setPreviewValue(props.component.id, val)
})
</script>

<style scoped>
.textarea-wrapper {
  position: relative;
  width: 100%;
  height: 100%;
}

.textarea-component {
  width: 100%;
  height: 100%;
  outline: none;
  font-family: inherit;
  box-sizing: border-box;
  transition: border-color 0.2s;
}

.textarea-component::placeholder {
  color: #c0c4cc;
}

.validation-error {
  position: absolute;
  top: 100%;
  left: 0;
  font-size: 11px;
  color: #f56c6c;
  margin-top: 2px;
  white-space: nowrap;
}
</style>
