// src/components/canvas/components/TextComponent.tsx
import { useMemo } from 'react'
import type { ComponentData } from '@/types'
import { useComponentStyle } from '@/hooks/useComponentStyle'

export default function TextComponent({ component }: { component: ComponentData }) {
  const baseStyle = useComponentStyle(component.style)
  const computedStyle = useMemo<React.CSSProperties>(
    () => ({
      ...baseStyle,
      color: component.style.color ?? '#333333',
      backgroundColor: component.style.backgroundColor ?? 'transparent',
      whiteSpace: 'pre-wrap',
      wordBreak: 'break-word',
      padding: '4px 8px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'flex-start',
      minHeight: '20px',
    }),
    [baseStyle, component.style.color, component.style.backgroundColor],
  )

  return <div style={computedStyle}>{(component.props.content as string) ?? ''}</div>
}

// src/components/canvas/components/TextComponent.vue
<template>
  <div class="text-component" :style="computedStyle">
    {{ component.props.content ?? '' }}
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { ComponentData } from '@/types'
import { useComponentStyle } from './composables/useComponentStyle'

const props = defineProps<{
  component: ComponentData
}>()

const { baseStyle } = useComponentStyle(props.component.style)

const computedStyle = computed(() => ({
  ...baseStyle.value,
  color: props.component.style.color ?? '#333333',
  backgroundColor: props.component.style.backgroundColor ?? 'transparent',
  whiteSpace: 'pre-wrap' as const,
  wordBreak: 'break-word' as const,
  padding: '4px 8px',
}))
</script>

<style scoped>
.text-component {
  width: 100%;
  height: 100%;
  display: flex;
  align-items: center;
  justify-content: flex-start;
  min-height: 20px;
  box-sizing: border-box;
}
</style>
