// src/components/canvas/EditorCanvas.tsx
import { useState, useEffect, useRef, useCallback } from 'react'
import { useEditorStore } from '@/stores/editorStore'
import type { ComponentData } from '@/types'
import { ComponentType } from '@/types'
import ComponentRenderer from './components/ComponentRenderer'
import styles from './EditorCanvas.module.css'

export default function EditorCanvas() {
  const currentPage = useEditorStore((s) => s.currentPage)
  const currentComponent = useEditorStore((s) => s.currentComponent)
  const canvasScale = useEditorStore((s) => s.canvasScale)
  const selectComponent = useEditorStore((s) => s.selectComponent)
  const clearSelectedComponents = useEditorStore((s) => s.clearSelectedComponents)
  const setCanvasScale = useEditorStore((s) => s.setCanvasScale)
  const addComponent = useEditorStore((s) => s.addComponent)
  const reorderComponent = useEditorStore((s) => s.reorderComponent)
  const createNewPage = useEditorStore((s) => s.createNewPage)

  // Resize state refs
  const isResizingRef = useRef(false)
  const resizeDirectionRef = useRef('')
  const resizeStartXRef = useRef(0)
  const resizeStartYRef = useRef(0)
  const originalWidthRef = useRef(0)
  const originalHeightRef = useRef(0)
  const resizeStartStyleRef = useRef<ComponentData['style'] | null>(null)
  const resizeComponentIdRef = useRef<string | null>(null)

  // Drag-to-reorder state
  const [dragOverIndex, setDragOverIndex] = useState<number | null>(null)
  const draggingIdRef = useRef<string | null>(null)

  // Resize handlers (only width/height, no top/left)
  const handleResize = useCallback((event: MouseEvent) => {
    const state = useEditorStore.getState()
    const compId = resizeComponentIdRef.current
    if (!isResizingRef.current || !compId) return

    const deltaX = (event.clientX - resizeStartXRef.current) / state.canvasScale
    const deltaY = (event.clientY - resizeStartYRef.current) / state.canvasScale
    const dir = resizeDirectionRef.current

    let newWidth = originalWidthRef.current
    let newHeight = originalHeightRef.current

    if (dir.includes('r')) newWidth = Math.max(20, originalWidthRef.current + deltaX)
    if (dir.includes('b')) newHeight = Math.max(20, originalHeightRef.current + deltaY)

    state.updateComponentStyleSilent(compId, { width: newWidth, height: newHeight })
  }, [])

  const stopResize = useCallback(() => {
    const state = useEditorStore.getState()
    const compId = resizeComponentIdRef.current
    if (isResizingRef.current && compId && resizeStartStyleRef.current) {
      const comp = state.getComponentById(compId)
      if (comp) {
        const hasChanged =
          comp.style.width !== resizeStartStyleRef.current.width ||
          comp.style.height !== resizeStartStyleRef.current.height
        if (hasChanged) {
          state.batchUpdateComponentStyle(compId, resizeStartStyleRef.current, {
            width: comp.style.width,
            height: comp.style.height,
          })
        }
      }
    }
    isResizingRef.current = false
    resizeStartStyleRef.current = null
    resizeComponentIdRef.current = null
    document.removeEventListener('mousemove', handleResize)
    document.removeEventListener('mouseup', stopResize)
  }, [handleResize])

  const startResize = useCallback(
    (component: ComponentData, direction: string, event: React.MouseEvent) => {
      isResizingRef.current = true
      resizeDirectionRef.current = direction
      resizeComponentIdRef.current = component.id
      resizeStartXRef.current = event.clientX
      resizeStartYRef.current = event.clientY
      originalWidthRef.current = component.style.width
      originalHeightRef.current = component.style.height
      resizeStartStyleRef.current = { ...component.style }

      document.addEventListener('mousemove', handleResize)
      document.addEventListener('mouseup', stopResize)
      event.preventDefault()
      event.stopPropagation()
    },
    [handleResize, stopResize],
  )

  const handleComponentClick = useCallback(
    (component: ComponentData, event: React.MouseEvent) => {
      selectComponent(component.id, event.shiftKey)
      event.stopPropagation()
    },
    [selectComponent],
  )

  const handleCanvasClick = useCallback(
    (event: React.MouseEvent) => {
      if (event.target === event.currentTarget) {
        clearSelectedComponents()
      }
    },
    [clearSelectedComponents],
  )

  // Drop from material panel
  const handleDragOver = useCallback((event: React.DragEvent) => {
    event.preventDefault()
    if (event.dataTransfer) event.dataTransfer.dropEffect = 'copy'
  }, [])

  const handleDrop = useCallback(
    (event: React.DragEvent) => {
      event.preventDefault()
      if (!event.dataTransfer || !currentPage) return
      const componentType = event.dataTransfer.getData('componentType') as ComponentType
      if (!componentType) return
      // Flow layout: just append, no position needed
      addComponent(componentType)
      setDragOverIndex(null)
    },
    [currentPage, addComponent],
  )

  // Drag-to-reorder handlers
  const handleReorderDragStart = useCallback((componentId: string, event: React.DragEvent) => {
    draggingIdRef.current = componentId
    event.dataTransfer.setData('reorderId', componentId)
    event.dataTransfer.effectAllowed = 'move'
  }, [])

  const handleReorderDragOver = useCallback((index: number, event: React.DragEvent) => {
    event.preventDefault()
    // Only show indicator for reorder (not material panel drops)
    if (draggingIdRef.current) {
      event.dataTransfer.dropEffect = 'move'
      setDragOverIndex(index)
    }
  }, [])

  const handleReorderDrop = useCallback(
    (targetIndex: number, event: React.DragEvent) => {
      event.preventDefault()
      event.stopPropagation()
      const sourceId = draggingIdRef.current
      if (sourceId) {
        reorderComponent(sourceId, targetIndex)
      }
      draggingIdRef.current = null
      setDragOverIndex(null)
    },
    [reorderComponent],
  )

  const handleReorderDragEnd = useCallback(() => {
    draggingIdRef.current = null
    setDragOverIndex(null)
  }, [])

  useEffect(() => {
    if (!currentPage) createNewPage()
  }, [])

  useEffect(() => {
    return () => {
      document.removeEventListener('mousemove', handleResize)
      document.removeEventListener('mouseup', stopResize)
    }
  }, [handleResize, stopResize])

  const resizeHandles = ['r', 'b', 'br'] as const

  return (
    <div className={styles.editorCanvas}>
      <div className={styles.canvasToolbar}>
        <div className={styles.btnGroup}>
          <button
            className={styles.toolBtn}
            onClick={() => setCanvasScale(Math.max(canvasScale - 0.1, 0.5))}
            disabled={canvasScale <= 0.5}
          >
            -
          </button>
          <button className={styles.toolBtn}>{Math.round(canvasScale * 100)}%</button>
          <button
            className={styles.toolBtn}
            onClick={() => setCanvasScale(Math.min(canvasScale + 0.1, 2))}
            disabled={canvasScale >= 2}
          >
            +
          </button>
          <button className={styles.toolBtn} onClick={() => setCanvasScale(1)}>
            1:1
          </button>
        </div>
      </div>

      <div
        className={styles.canvasContainer}
        style={{ transform: `scale(${canvasScale})`, transformOrigin: 'center top' }}
        onMouseDown={handleCanvasClick}
        onDragOver={handleDragOver}
        onDrop={handleDrop}
      >
        <div
          className={styles.canvasBackground}
          data-testid="canvas-background"
          style={{ backgroundColor: currentPage?.style.backgroundColor || '#ffffff' }}
        >
          {currentPage?.components.map((component, index) => (
            <div
              key={component.id}
              className={`${styles.componentWrapper} ${currentComponent?.id === component.id ? styles.selected : ''} ${dragOverIndex === index ? styles.dragOverIndicator : ''}`}
              data-testid="component-wrapper"
              draggable
              style={{
                width: `${component.style.width}px`,
                height: `${component.style.height}px`,
              }}
              onClick={(e) => handleComponentClick(component, e)}
              onDragStart={(e) => handleReorderDragStart(component.id, e)}
              onDragOver={(e) => handleReorderDragOver(index, e)}
              onDrop={(e) => handleReorderDrop(index, e)}
              onDragEnd={handleReorderDragEnd}
              onDragLeave={() => {
                if (draggingIdRef.current) setDragOverIndex(null)
              }}
            >
              <ComponentRenderer component={component} />

              {currentComponent?.id === component.id && (
                <div className={styles.resizeHandles}>
                  {resizeHandles.map((dir) => (
                    <div
                      key={dir}
                      className={`${styles.handle} ${styles[`handle_${dir}`]}`}
                      onMouseDown={(e) => {
                        e.stopPropagation()
                        startResize(component, dir, e)
                      }}
                    />
                  ))}
                </div>
              )}
            </div>
          ))}

          {currentPage?.components.length === 0 && (
            <div className={styles.emptyHint}>
              <span style={{ fontSize: 36, color: '#ddd' }}>{'\u2b07'}</span>
              <p>
                {
                  '\u4ece\u5de6\u4fa7\u62d6\u5165\u7ec4\u4ef6\uff0c\u6216\u4f7f\u7528 AI \u52a9\u624b\u751f\u6210\u9875\u9762'
                }
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

// src/components/EditorCanvas.vue
<template>
  <div class="editor-canvas">
    <div class="canvas-toolbar">
      <el-button-group>
        <el-button @click="zoomOut" :disabled="canvasScale <= 0.5">
          <el-icon><ZoomOut /></el-icon>
        </el-button>
        <el-button>{{ Math.round(canvasScale * 100) }}%</el-button>
        <el-button @click="zoomIn" :disabled="canvasScale >= 2">
          <el-icon><ZoomIn /></el-icon>
        </el-button>
        <el-button @click="resetZoom">
          <el-icon><FullScreen /></el-icon>
        </el-button>
      </el-button-group>
      
      <el-switch
        v-model="snapToGrid"
        active-text="吸附网格"
        inactive-text="自由拖拽"
      />
      
      <el-switch
        v-model="showGuidelines"
        active-text="显示辅助线"
        inactive-text="隐藏辅助线"
      />
    </div>
    
    <div 
      class="canvas-container"
      :style="{
        transform: `scale(${canvasScale})`,
        transformOrigin: 'center center'
      }"
      @mousedown="handleCanvasClick"
      @dragover="handleDragOver"
      @drop="handleDrop"
    >
      <div
        class="canvas-background"
        data-testid="canvas-background"
        :style="{
          width: `${currentPage?.style.width || 1200}px`,
          height: `${currentPage?.style.height || 800}px`,
          backgroundColor: currentPage?.style.backgroundColor || '#ffffff'
        }"
      >
        <div
          v-for="component in currentPage?.components"
          :key="component.id"
          class="component-wrapper"
          data-testid="component-wrapper"
          :class="{ selected: currentComponent?.id === component.id }"
          :style="{
            top: `${component.style.top}px`,
            left: `${component.style.left}px`,
            width: `${component.style.width}px`,
            height: `${component.style.height}px`,
            zIndex: currentComponent?.id === component.id
              ? component.style.zIndex + 1000
              : component.style.zIndex,
            transform: `rotate(${component.style.rotate}deg)`
          }"
          @mousedown="handleComponentMouseDown(component, $event)"
        >
          <ComponentRenderer
            :component="component"
            class="component-content"
          />
          
          <div v-if="currentComponent?.id === component.id" class="component-resize-handles">
            <div class="handle handle-tl" @mousedown.stop="startResize(component, 'tl', $event)"></div>
            <div class="handle handle-tr" @mousedown.stop="startResize(component, 'tr', $event)"></div>
            <div class="handle handle-bl" @mousedown.stop="startResize(component, 'bl', $event)"></div>
            <div class="handle handle-br" @mousedown.stop="startResize(component, 'br', $event)"></div>
            <div class="handle handle-t" @mousedown.stop="startResize(component, 't', $event)"></div>
            <div class="handle handle-r" @mousedown.stop="startResize(component, 'r', $event)"></div>
            <div class="handle handle-b" @mousedown.stop="startResize(component, 'b', $event)"></div>
            <div class="handle handle-l" @mousedown.stop="startResize(component, 'l', $event)"></div>
          </div>
        </div>
        
        <div v-if="showGuidelines" class="guidelines">
          <!-- 简洁的十字辅助线 -->
          <div class="guideline vertical center" :style="{ left: '50%' }"></div>
          <div class="guideline horizontal center" :style="{ top: '50%' }"></div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, onUnmounted } from 'vue'
import { useEditorStore } from '@/stores/editor'
import type { ComponentData } from '@/types'
import { ComponentType } from '@/types'
import ComponentRenderer from './components/ComponentRenderer.vue'

const editorStore = useEditorStore()

const currentPage = computed(() => editorStore.currentPage)
const currentComponent = computed(() => editorStore.currentComponent)
const canvasScale = computed(() => editorStore.canvasScale)
const snapToGrid = computed({
  get: () => editorStore.snapToGrid,
  set: (value) => editorStore.setSnapToGrid(value)
})
const showGuidelines = computed({
  get: () => editorStore.showGuidelines,
  set: (value) => editorStore.setShowGuidelines(value)
})

const selectComponent = (component: ComponentData) => {
  editorStore.selectComponent(component.id)
}

const handleComponentMouseDown = (component: ComponentData, event: MouseEvent) => {
  // 支持 shift 多选
  editorStore.selectComponent(component.id, event.shiftKey)
  // 多选拖拽
  if (editorStore.selectedComponentIds.length > 1) {
    editorStore.startMultiDrag(event)
  } else {
    startDrag(component, event)
  }
  event.stopPropagation()
  event.preventDefault()
}

const handleCanvasClick = (event: MouseEvent) => {
  if (event.target === event.currentTarget) {
    editorStore.clearSelectedComponents()
  }
}

const zoomIn = () => {
  editorStore.setCanvasScale(Math.min(canvasScale.value + 0.1, 2))
}

const zoomOut = () => {
  editorStore.setCanvasScale(Math.max(canvasScale.value - 0.1, 0.5))
}

const resetZoom = () => {
  editorStore.setCanvasScale(1)
}

const handleDragOver = (event: DragEvent) => {
  event.preventDefault()
  if (event.dataTransfer) {
    event.dataTransfer.dropEffect = 'copy'
  }
}

const handleDrop = (event: DragEvent) => {
  event.preventDefault()
  
  if (!event.dataTransfer || !editorStore.currentPage) return
  
  const componentType = event.dataTransfer.getData('componentType') as ComponentType
  if (!componentType) return
  
  // 获取画布背景的实际位置（组件应该相对于canvas-background定位）
  const canvasBackground = document.querySelector('.canvas-background') as HTMLElement
  if (!canvasBackground) return
  
  const canvasRect = canvasBackground.getBoundingClientRect()
  
  // 计算相对于画布背景的精确位置
  // 注意：getBoundingClientRect返回的是实际渲染位置，已经包含了缩放
  // 所以我们需要将鼠标位置转换为画布坐标系中的位置
  const scale = canvasScale.value
  const offsetX = (event.clientX - canvasRect.left) / scale
  const offsetY = (event.clientY - canvasRect.top) / scale
  
  // 添加新组件到画布，放置在鼠标位置
  editorStore.addComponent(componentType, {
    left: Math.max(0, offsetX),
    top: Math.max(0, offsetY)
  })
}

let isDragging = false
let dragStartX = 0
let dragStartY = 0
let originalLeft = 0
let originalTop = 0
let dragStartStyle: ComponentData['style'] | null = null  // 拖拽开始时的完整样式快照

const startDrag = (component: ComponentData, event: MouseEvent) => {
  isDragging = true
  
  // 记录拖拽开始时的鼠标位置和组件位置
  dragStartX = event.clientX
  dragStartY = event.clientY
  originalLeft = component.style.left
  originalTop = component.style.top
  dragStartStyle = { ...component.style }  // 保存完整样式快照
  
  document.addEventListener('mousemove', handleDrag)
  document.addEventListener('mouseup', stopDrag)
  event.preventDefault()
}

const handleDrag = (event: MouseEvent) => {
  if (!isDragging || !currentComponent.value) return
  
  // 计算鼠标移动的偏移量（考虑缩放）
  const deltaX = (event.clientX - dragStartX) / canvasScale.value
  const deltaY = (event.clientY - dragStartY) / canvasScale.value
  
  // 计算新位置
  let newLeft = originalLeft + deltaX
  let newTop = originalTop + deltaY
  
  // 网格吸附功能
  if (snapToGrid.value) {
    newLeft = Math.round(newLeft / 10) * 10
    newTop = Math.round(newTop / 10) * 10
  }
  
  // 确保位置不超出画布边界
  newLeft = Math.max(0, newLeft)
  newTop = Math.max(0, newTop)
  
  // 使用静默更新，不记录历史（拖拽过程中高频调用）
  editorStore.updateComponentStyleSilent(currentComponent.value.id, {
    left: newLeft,
    top: newTop
  })
}

const stopDrag = () => {
  // 拖拽结束时，如果位置有变化，记录一次历史
  if (isDragging && currentComponent.value && dragStartStyle) {
    const currentStyle = currentComponent.value.style
    // 只有位置真正变化才记录历史
    if (currentStyle.left !== dragStartStyle.left || currentStyle.top !== dragStartStyle.top) {
      editorStore.batchUpdateComponentStyle(
        currentComponent.value.id,
        dragStartStyle,
        { left: currentStyle.left, top: currentStyle.top }
      )
    }
  }
  
  isDragging = false
  dragStartStyle = null
  document.removeEventListener('mousemove', handleDrag)
  document.removeEventListener('mouseup', stopDrag)
}

let isResizing = false
let resizeDirection = ''
let resizeStartX = 0
let resizeStartY = 0
let originalWidth = 0
let originalHeight = 0
let originalLeftResize = 0
let originalTopResize = 0
let resizeStartStyle: ComponentData['style'] | null = null  // 缩放开始时的完整样式快照

const startResize = (component: ComponentData, direction: string, event: MouseEvent) => {
  isResizing = true
  resizeDirection = direction
  resizeStartX = event.clientX
  resizeStartY = event.clientY
  originalWidth = component.style.width
  originalHeight = component.style.height
  originalLeftResize = component.style.left
  originalTopResize = component.style.top
  resizeStartStyle = { ...component.style }  // 保存完整样式快照
  
  document.addEventListener('mousemove', handleResize)
  document.addEventListener('mouseup', stopResize)
  event.preventDefault()
  event.stopPropagation()
}

const handleResize = (event: MouseEvent) => {
  if (!isResizing || !currentComponent.value) return
  
  const deltaX = (event.clientX - resizeStartX) / canvasScale.value
  const deltaY = (event.clientY - resizeStartY) / canvasScale.value
  
  let newWidth = originalWidth
  let newHeight = originalHeight
  let newLeft = originalLeftResize
  let newTop = originalTopResize
  
  switch (resizeDirection) {
    case 'tl':
      newWidth = Math.max(20, originalWidth - deltaX)
      newHeight = Math.max(20, originalHeight - deltaY)
      newLeft = originalLeftResize + (originalWidth - newWidth)
      newTop = originalTopResize + (originalHeight - newHeight)
      break
    case 'tr':
      newWidth = Math.max(20, originalWidth + deltaX)
      newHeight = Math.max(20, originalHeight - deltaY)
      newTop = originalTopResize + (originalHeight - newHeight)
      break
    case 'bl':
      newWidth = Math.max(20, originalWidth - deltaX)
      newHeight = Math.max(20, originalHeight + deltaY)
      newLeft = originalLeftResize + (originalWidth - newWidth)
      break
    case 'br':
      newWidth = Math.max(20, originalWidth + deltaX)
      newHeight = Math.max(20, originalHeight + deltaY)
      break
    case 't':
      newHeight = Math.max(20, originalHeight - deltaY)
      newTop = originalTopResize + (originalHeight - newHeight)
      break
    case 'b':
      newHeight = Math.max(20, originalHeight + deltaY)
      break
    case 'l':
      newWidth = Math.max(20, originalWidth - deltaX)
      newLeft = originalLeftResize + (originalWidth - newWidth)
      break
    case 'r':
      newWidth = Math.max(20, originalWidth + deltaX)
      break
  }
  
  // 使用静默更新，不记录历史（缩放过程中高频调用）
  editorStore.updateComponentStyleSilent(currentComponent.value.id, {
    width: newWidth,
    height: newHeight,
    left: newLeft,
    top: newTop
  })
}

const stopResize = () => {
  // 缩放结束时，如果样式有变化，记录一次历史
  if (isResizing && currentComponent.value && resizeStartStyle) {
    const currentStyle = currentComponent.value.style
    const hasChanged = 
      currentStyle.width !== resizeStartStyle.width ||
      currentStyle.height !== resizeStartStyle.height ||
      currentStyle.left !== resizeStartStyle.left ||
      currentStyle.top !== resizeStartStyle.top
    
    if (hasChanged) {
      editorStore.batchUpdateComponentStyle(
        currentComponent.value.id,
        resizeStartStyle,
        {
          width: currentStyle.width,
          height: currentStyle.height,
          left: currentStyle.left,
          top: currentStyle.top
        }
      )
    }
  }
  
  isResizing = false
  resizeStartStyle = null
  document.removeEventListener('mousemove', handleResize)
  document.removeEventListener('mouseup', stopResize)
}

onMounted(() => {
  // 确保页面在组件挂载时已经创建
  if (!currentPage.value) {
    editorStore.createNewPage()
  }
  
  // 添加拖放区域初始化检查
  const canvasContainer = document.querySelector('.canvas-container') as HTMLElement
  if (canvasContainer) {
    // 确保拖放区域已准备好
    console.log('Canvas container ready for drag and drop')
  }
})

onUnmounted(() => {
  document.removeEventListener('mousemove', handleDrag)
  document.removeEventListener('mouseup', stopDrag)
  document.removeEventListener('mousemove', handleResize)
  document.removeEventListener('mouseup', stopResize)
})
</script>

<style scoped>
.editor-canvas {
  flex: 1;
  display: flex;
  flex-direction: column;
  background: #f5f5f5;
  overflow: hidden;
}

.canvas-toolbar {
  padding: 10px;
  background: white;
  border-bottom: 1px solid #e0e0e0;
  display: flex;
  gap: 20px;
  align-items: center;
}

.canvas-container {
  flex: 1;
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 20px;
  overflow: auto;
  min-height: 400px;
  cursor: default;
  max-width: 100%;
}

.canvas-background {
  position: relative;
  background: white;
  box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
  border: 1px solid #e0e0e0;
  min-width: 800px;
  min-height: 600px;
  max-width: 100%;
  max-height: 100%;
}

.component-wrapper {
  position: absolute;
  cursor: move;
  border: 2px solid transparent;
  transition: border-color 0.2s;
}

.component-wrapper.selected {
  border-color: #409eff;
}

.component-content {
  width: 100%;
  height: 100%;
}

.component-resize-handles {
  position: absolute;
  top: -4px;
  left: -4px;
  right: -4px;
  bottom: -4px;
  pointer-events: none;
}

.component-resize-handles .handle {
  position: absolute;
  width: 8px;
  height: 8px;
  background: #409eff;
  border: 1px solid white;
  border-radius: 1px;
  pointer-events: all;
  cursor: nwse-resize;
}

.handle-tl { top: -4px; left: -4px; cursor: nw-resize; }
.handle-tr { top: -4px; right: -4px; cursor: ne-resize; }
.handle-bl { bottom: -4px; left: -4px; cursor: sw-resize; }
.handle-br { bottom: -4px; right: -4px; cursor: se-resize; }
.handle-t { top: -4px; left: 50%; margin-left: -4px; cursor: n-resize; }
.handle-r { right: -4px; top: 50%; margin-top: -4px; cursor: e-resize; }
.handle-b { bottom: -4px; left: 50%; margin-left: -4px; cursor: s-resize; }
.handle-l { left: -4px; top: 50%; margin-top: -4px; cursor: w-resize; }

.guidelines {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  pointer-events: none;
  z-index: 1;
}

.guideline {
  position: absolute;
}

.guideline.vertical {
  width: 2px;
  top: 0;
  bottom: 0;
}

.guideline.horizontal {
  height: 2px;
  left: 0;
  right: 0;
}

.guideline.center {
  background: rgba(64, 158, 255, 0.3);
  box-shadow: 0 0 2px rgba(64, 158, 255, 0.5);
}
</style>
