// src/components/editor/Editor.tsx
import { useState, useEffect, useCallback } from 'react'
import { useEditorStore } from '@/stores/editorStore'
import { useHistoryStore } from '@/stores/historyStore'
import { PreviewProvider } from '@/context/PreviewContext'
import ComponentPanel from '../material/ComponentPanel'
import EditorCanvas from '../canvas/EditorCanvas'
import PropertyPanel from '../property/PropertyPanel'
import LivePreviewPanel from './LivePreviewPanel'
import AIPanel from './AIPanel'
import { Modal } from '@/components/ui/Modal'
import { useToast } from '@/components/ui/Toast'
import { savePage, createPage, fetchPageList, fetchPage } from '@/services/api'
import type { PageListItem } from '@/services/api'
import styles from './Editor.module.css'

export default function Editor() {
  const currentPage = useEditorStore((s) => s.currentPage)
  const createNewPage = useEditorStore((s) => s.createNewPage)
  const loadPageData = useEditorStore((s) => s.loadPageData)
  const exportPageData = useEditorStore((s) => s.exportPageData)
  const clearPreviewState = useEditorStore((s) => s.clearPreviewState)
  const canUndo = useHistoryStore((s) => s.canUndo)
  const canRedo = useHistoryStore((s) => s.canRedo)
  const undo = useHistoryStore((s) => s.undo)
  const redo = useHistoryStore((s) => s.redo)
  const toast = useToast()

  const [livePreviewVisible, setLivePreviewVisible] = useState(false)
  const [aiPanelOpen, setAiPanelOpen] = useState(false)
  const [pageListVisible, setPageListVisible] = useState(false)
  const [isSaving, setIsSaving] = useState(false)
  const [pageList, setPageList] = useState<PageListItem[]>([])

  useEffect(() => {
    if (!livePreviewVisible) clearPreviewState()
  }, [livePreviewVisible, clearPreviewState])

  useEffect(() => {
    if (!currentPage) createNewPage()
  }, [])

  const handleExport = useCallback(() => {
    const pageData = exportPageData()
    if (pageData) {
      const blob = new Blob([pageData], { type: 'application/json' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `${currentPage?.title || 'page'}.json`
      a.click()
      URL.revokeObjectURL(url)
    } else {
      toast.warning('没有页面数据可导出')
    }
  }, [exportPageData, currentPage, toast])

  const handleSave = useCallback(async () => {
    const page = currentPage
    if (!page) {
      toast.warning('当前没有可保存的页面')
      return
    }
    setIsSaving(true)
    try {
      const listRes = await fetchPageList().catch(() => [] as PageListItem[])
      const exists = listRes.some((p) => p.id === page.id)
      const saved = exists ? await savePage(page.id, page) : await createPage(page)
      toast.success(`页面「${saved.title}」保存成功`)
    } catch (e) {
      toast.error(e instanceof Error ? e.message : '保存失败')
    } finally {
      setIsSaving(false)
    }
  }, [currentPage, toast])

  const handleOpenPageList = useCallback(async () => {
    try {
      const list = await fetchPageList()
      setPageList(list)
      setPageListVisible(true)
    } catch {
      toast.error('获取页面列表失败，请确认后端服务已启动')
    }
  }, [toast])

  const handleLoadPage = useCallback(
    async (item: PageListItem) => {
      if (!window.confirm(`加载页面「${item.title}」将替换当前画布内容，是否继续？`)) return
      try {
        const pageData = await fetchPage(item.id)
        loadPageData(pageData)
        setPageListVisible(false)
        toast.success(`页面「${pageData.title}」已加载`)
      } catch (e) {
        toast.error(e instanceof Error ? e.message : '加载失败')
      }
    },
    [loadPageData, toast],
  )

  return (
    <PreviewProvider isPreview={false}>
      <div className={styles.container}>
        <div className={styles.header}>
          <div className={styles.headerLeft}>
            <h1>可视化页面编辑器</h1>
            <span className={styles.pageTitle}>{currentPage?.title || '未命名页面'}</span>
          </div>

          <div className={styles.headerCenter}>
            <div className={styles.btnGroup}>
              <button
                className={styles.btn}
                data-testid="btn-undo"
                onClick={undo}
                disabled={!canUndo()}
              >
                {'← 撤销'}
              </button>
              <button
                className={styles.btn}
                data-testid="btn-redo"
                onClick={redo}
                disabled={!canRedo()}
              >
                {'重做 →'}
              </button>
            </div>
            <button
              className={`${styles.btn} ${styles.btnPrimary}`}
              onClick={() => setLivePreviewVisible(true)}
            >
              {'▶ 实时预览'}
            </button>
            <button className={`${styles.btn} ${styles.btnSuccess}`} onClick={handleExport}>
              {'⬇ 导出JSON'}
            </button>
          </div>

          <div className={styles.headerRight}>
            <button className={styles.btn} onClick={handleOpenPageList}>
              打开
            </button>
            <button
              className={`${styles.btn} ${styles.btnPrimary}`}
              onClick={handleSave}
              disabled={isSaving}
            >
              {isSaving ? '保存中...' : '保存'}
            </button>
            <button className={styles.btn} onClick={() => createNewPage()}>
              新建页面
            </button>
          </div>
        </div>

        <div className={styles.body}>
          <ComponentPanel />
          <EditorCanvas />
          <PropertyPanel />
        </div>

        <Modal
          open={livePreviewVisible}
          title="实时预览"
          width="90%"
          onClose={() => setLivePreviewVisible(false)}
        >
          <LivePreviewPanel />
        </Modal>

        <Modal
          open={pageListVisible}
          title="打开页面"
          width="600px"
          onClose={() => setPageListVisible(false)}
          footer={
            <button className={styles.btn} onClick={() => setPageListVisible(false)}>
              关闭
            </button>
          }
        >
          {pageList.length === 0 ? (
            <div className={styles.emptyState}>暂无已保存的页面</div>
          ) : (
            <table className={styles.pageTable}>
              <thead>
                <tr>
                  <th>页面名称</th>
                  <th>组件数</th>
                  <th>最后保存</th>
                  <th>操作</th>
                </tr>
              </thead>
              <tbody>
                {pageList.map((row) => (
                  <tr key={row.id}>
                    <td>{row.title}</td>
                    <td style={{ textAlign: 'center' }}>{row.componentCount}</td>
                    <td>{new Date(row.updatedAt).toLocaleString()}</td>
                    <td>
                      <button className={styles.linkBtn} onClick={() => handleLoadPage(row)}>
                        打开
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </Modal>

        <AIPanel open={aiPanelOpen} onClose={() => setAiPanelOpen(!aiPanelOpen)} />
      </div>
    </PreviewProvider>
  )
}

// src/components/Editor.vue
<template>
  <div class="page-editor-container">
    <div class="editor-header">
      <div class="header-left">
        <h1>可视化页面编辑器</h1>
        <span class="page-title">{{ currentPage?.title || '未命名页面' }}</span>
      </div>
      
      <div class="header-center">
        <el-button-group>
          <el-button data-testid="btn-undo" @click="handleUndo" :disabled="!canUndo">
            <el-icon><RefreshLeft /></el-icon>
            撤销
          </el-button>
          <el-button data-testid="btn-redo" @click="handleRedo" :disabled="!canRedo">
            <el-icon><RefreshRight /></el-icon>
            重做
          </el-button>
        </el-button-group>
        
        <el-button @click="handlePreview" type="primary">
          <el-icon><View /></el-icon>
          预览
        </el-button>
        
        <el-button @click="handleExport" type="success">
          <el-icon><Download /></el-icon>
          导出JSON
        </el-button>
      </div>
      
      <div class="header-right">
        <el-button @click="handleOpenPageList">
          <el-icon><FolderOpened /></el-icon>
          打开
        </el-button>
        <el-button @click="handleSave" :loading="isSaving" type="primary">
          <el-icon><Document /></el-icon>
          保存
        </el-button>
        <el-button @click="handleNewPage">
          <el-icon><Plus /></el-icon>
          新建页面
        </el-button>
      </div>
    </div>
    
    <div class="editor-body">
      <ComponentPanel />
      <EditorCanvas />
      <PropertyPanel />
    </div>
    
    <el-dialog
      v-model="previewVisible"
      title="页面预览"
      width="80%"
      top="5vh"
    >
      <div class="preview-container">
        <div 
          class="preview-content"
          :style="{
            width: `${currentPage?.style.width || 1200}px`,
            height: `${currentPage?.style.height || 800}px`,
            backgroundColor: currentPage?.style.backgroundColor || '#ffffff',
            margin: '0 auto'
          }"
        >
          <div
            v-for="component in currentPage?.components"
            :key="component.id"
            class="preview-component"
            :style="{
              top: `${component.style.top}px`,
              left: `${component.style.left}px`,
              width: `${component.style.width}px`,
              height: `${component.style.height}px`,
              zIndex: component.style.zIndex,
              transform: `rotate(${component.style.rotate}deg)`
            }"
          >
            <ComponentRenderer :component="component" />
          </div>
        </div>
      </div>
      
      <template #footer>
        <el-button @click="previewVisible = false">关闭</el-button>
      </template>
    </el-dialog>

    <!-- 页面列表弹窗 -->
    <el-dialog
      v-model="pageListVisible"
      title="打开页面"
      width="600px"
    >
      <div v-if="pageList.length === 0" class="page-list-empty">
        <el-empty description="暂无已保存的页面" />
      </div>
      <el-table v-else :data="pageList" style="width: 100%" highlight-current-row>
        <el-table-column prop="title" label="页面名称" min-width="150" />
        <el-table-column prop="componentCount" label="组件数" width="80" align="center" />
        <el-table-column label="最后保存" width="170">
          <template #default="{ row }">
            {{ new Date(row.updatedAt).toLocaleString() }}
          </template>
        </el-table-column>
        <el-table-column label="操作" width="80" align="center">
          <template #default="{ row }">
            <el-button type="primary" link @click="handleLoadPage(row)">打开</el-button>
          </template>
        </el-table-column>
      </el-table>

      <template #footer>
        <el-button @click="pageListVisible = false">关闭</el-button>
      </template>
    </el-dialog>

    <!-- AI 助手面板 -->
    <AIPanel v-model="aiPanelVisible" />
  </div>
</template>

<script setup lang="ts">
// eslint-disable-next-line vue/multi-word-component-names
import { ref, computed, onMounted } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { useEditorStore } from '@/stores/editor'
import { useHistoryStore } from '@/stores/history'
import ComponentPanel from './ComponentPanel.vue'
import EditorCanvas from './EditorCanvas.vue'
import PropertyPanel from './PropertyPanel.vue'
import ComponentRenderer from './components/ComponentRenderer.vue'
import AIPanel from './AIPanel.vue'
import {
  RefreshLeft,
  RefreshRight,
  View,
  Download,
  Document,
  Plus,
  FolderOpened
} from '@element-plus/icons-vue'
import { savePage, createPage, fetchPageList, fetchPage } from '@/services/api'
import type { PageListItem } from '@/services/api'

const editorStore = useEditorStore()
const historyStore = useHistoryStore()

const previewVisible = ref(false)
const pageListVisible = ref(false)
const aiPanelVisible = ref(false)
const isSaving = ref(false)
const pageList = ref<PageListItem[]>([])

const currentPage = computed(() => editorStore.currentPage)
const canUndo = computed(() => historyStore.canUndo())
const canRedo = computed(() => historyStore.canRedo())

const handleUndo = () => {
  historyStore.undo()
}

const handleRedo = () => {
  historyStore.redo()
}

const handlePreview = () => {
  previewVisible.value = true
}

const handleExport = () => {
  const pageData = editorStore.exportPageData()
  if (pageData) {
    const blob = new Blob([pageData], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${currentPage.value?.title || 'page'}.json`
    a.click()
    URL.revokeObjectURL(url)
  } else {
    ElMessage.warning('没有页面数据可导出')
  }
}

/** 保存当前页面到后端 */
const handleSave = async () => {
  const page = currentPage.value
  if (!page) {
    ElMessage.warning('当前没有可保存的页面')
    return
  }

  isSaving.value = true
  try {
    // 判断是新建还是更新：若后端已有此 id 则 PUT，否则 POST
    let saved
    const listRes = await fetchPageList().catch(() => [] as PageListItem[])
    const exists = listRes.some((p) => p.id === page.id)

    if (exists) {
      saved = await savePage(page.id, page)
    } else {
      saved = await createPage(page)
    }

    ElMessage.success(`页面「${saved.title}」保存成功`)
  } catch (e) {
    const msg = e instanceof Error ? e.message : '保存失败'
    ElMessage.error(msg)
  } finally {
    isSaving.value = false
  }
}

/** 新建页面 */
const handleNewPage = () => {
  editorStore.createNewPage()
}

/** 打开页面列表 */
const handleOpenPageList = async () => {
  try {
    pageList.value = await fetchPageList()
    pageListVisible.value = true
  } catch {
    ElMessage.error('获取页面列表失败，请确认后端服务已启动')
  }
}

/** 加载选中的页面 */
const handleLoadPage = async (item: PageListItem) => {
  try {
    await ElMessageBox.confirm(
      `加载页面「${item.title}」将替换当前画布内容，是否继续？`,
      '加载页面',
      { type: 'warning', confirmButtonText: '确定', cancelButtonText: '取消' }
    )

    const pageData = await fetchPage(item.id)
    // 将后端数据写入 store
    editorStore.loadPageData(pageData)
    pageListVisible.value = false
    ElMessage.success(`页面「${pageData.title}」已加载`)
  } catch (e) {
    // 用户取消不报错
    if (e !== 'cancel') {
      const msg = e instanceof Error ? e.message : '加载失败'
      ElMessage.error(msg)
    }
  }
}

// 初始化：若无当前页面则创建一个默认页面
onMounted(() => {
  if (!currentPage.value) {
    editorStore.createNewPage()
  }
})
</script>

<style scoped>
.page-editor-container {
  width: 100vw;
  height: 100vh;
  display: flex;
  flex-direction: column;
  background: #f5f5f5;
  overflow: hidden;
}

.editor-header {
  height: 60px;
  background: white;
  border-bottom: 1px solid #e0e0e0;
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 20px;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
}

.header-left {
  display: flex;
  align-items: center;
  gap: 16px;
}

.header-left h1 {
  margin: 0;
  font-size: 18px;
  font-weight: 600;
  color: #333;
}

.page-title {
  color: #666;
  font-size: 14px;
}

.header-center {
  display: flex;
  align-items: center;
  gap: 12px;
}

.header-right {
  display: flex;
  align-items: center;
  gap: 8px;
}

.editor-body {
  flex: 1;
  display: flex;
  overflow: hidden;
}

.preview-container {
  max-height: 70vh;
  overflow: auto;
  display: flex;
  justify-content: center;
  padding: 20px;
}

.preview-content {
  position: relative;
  border: 1px solid #e0e0e0;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
}

.preview-component {
  position: absolute;
  pointer-events: none;
}

.preview-component > * {
  width: 100%;
  height: 100%;
}
</style>
